import { AddressingMode } from "./src/cpu/cpuAddressingMode.ts";
import { ICPU } from "./src/interface/ICPU.ts";

const addressingModeMap: { [opcode: number]: AddressingMode } = {
  0x00: AddressingMode.NoneAddressing,
  0xea: AddressingMode.NoneAddressing,

  0x69: AddressingMode.Immediate,
  0x65: AddressingMode.ZeroPage,
  0x75: AddressingMode.ZeroPage_X,
  0x6d: AddressingMode.Absolute,
  0x7d: AddressingMode.Absolute_X,
  0x79: AddressingMode.Absolute_Y,
  0x61: AddressingMode.Indirect_X,
  0x71: AddressingMode.Indirect_Y,

  0xe9: AddressingMode.Immediate,
  0xe5: AddressingMode.ZeroPage,
  0xf5: AddressingMode.ZeroPage_X,
  0xed: AddressingMode.Absolute,
  0xfd: AddressingMode.Absolute_X,
  0xf9: AddressingMode.Absolute_Y,
  0xe1: AddressingMode.Indirect_X,
  0xf1: AddressingMode.Indirect_Y,

  0x29: AddressingMode.Immediate,
  0x25: AddressingMode.ZeroPage,
  0x35: AddressingMode.ZeroPage_X,
  0x2d: AddressingMode.Absolute,
  0x3d: AddressingMode.Absolute_X,
  0x39: AddressingMode.Absolute_Y,
  0x21: AddressingMode.Indirect_X,
  0x31: AddressingMode.Indirect_Y,

  0x49: AddressingMode.Immediate,
  0x45: AddressingMode.ZeroPage,
  0x55: AddressingMode.ZeroPage_X,
  0x4d: AddressingMode.Absolute,
  0x5d: AddressingMode.Absolute_X,
  0x59: AddressingMode.Absolute_Y,
  0x41: AddressingMode.Indirect_X,
  0x51: AddressingMode.Indirect_Y,

  0x09: AddressingMode.Immediate,
  0x05: AddressingMode.ZeroPage,
  0x15: AddressingMode.ZeroPage_X,
  0x0d: AddressingMode.Absolute,
  0x1d: AddressingMode.Absolute_X,
  0x19: AddressingMode.Absolute_Y,
  0x01: AddressingMode.Indirect_X,
  0x11: AddressingMode.Indirect_Y,

  0x0a: AddressingMode.NoneAddressing,
  0x06: AddressingMode.ZeroPage,
  0x16: AddressingMode.ZeroPage_X,
  0x0e: AddressingMode.Absolute,
  0x1e: AddressingMode.Absolute_X,

  0x4a: AddressingMode.NoneAddressing,
  0x46: AddressingMode.ZeroPage,
  0x56: AddressingMode.ZeroPage_X,
  0x4e: AddressingMode.Absolute,
  0x5e: AddressingMode.Absolute_X,

  0x2a: AddressingMode.NoneAddressing,
  0x26: AddressingMode.ZeroPage,
  0x36: AddressingMode.ZeroPage_X,
  0x2e: AddressingMode.Absolute,
  0x3e: AddressingMode.Absolute_X,

  0x6a: AddressingMode.NoneAddressing,
  0x66: AddressingMode.ZeroPage,
  0x76: AddressingMode.ZeroPage_X,
  0x6e: AddressingMode.Absolute,
  0x7e: AddressingMode.Absolute_X,

  0xe6: AddressingMode.ZeroPage,
  0xf6: AddressingMode.ZeroPage_X,
  0xee: AddressingMode.Absolute,
  0xfe: AddressingMode.Absolute_X,

  0xe8: AddressingMode.NoneAddressing,
  0xc8: AddressingMode.NoneAddressing,

  0xc6: AddressingMode.ZeroPage,
  0xd6: AddressingMode.ZeroPage_X,
  0xce: AddressingMode.Absolute,
  0xde: AddressingMode.Absolute_X,

  0xca: AddressingMode.NoneAddressing,
  0x88: AddressingMode.NoneAddressing,

  0xc9: AddressingMode.Immediate,
  0xc5: AddressingMode.ZeroPage,
  0xd5: AddressingMode.ZeroPage_X,
  0xcd: AddressingMode.Absolute,
  0xdd: AddressingMode.Absolute_X,
  0xd9: AddressingMode.Absolute_Y,
  0xc1: AddressingMode.Indirect_X,
  0xd1: AddressingMode.Indirect_Y,

  0xc0: AddressingMode.Immediate,
  0xc4: AddressingMode.ZeroPage,
  0xcc: AddressingMode.Absolute,

  0xe0: AddressingMode.Immediate,
  0xe4: AddressingMode.ZeroPage,
  0xec: AddressingMode.Absolute,

  0x4c: AddressingMode.NoneAddressing,
  0x6c: AddressingMode.NoneAddressing,

  0x20: AddressingMode.NoneAddressing,
  0x60: AddressingMode.NoneAddressing,

  0x40: AddressingMode.NoneAddressing,

  0xd0: AddressingMode.NoneAddressing,
  0x70: AddressingMode.NoneAddressing,
  0x50: AddressingMode.NoneAddressing,
  0x30: AddressingMode.NoneAddressing,
  0xf0: AddressingMode.NoneAddressing,
  0xb0: AddressingMode.NoneAddressing,
  0x90: AddressingMode.NoneAddressing,
  0x10: AddressingMode.NoneAddressing,

  0x24: AddressingMode.ZeroPage,
  0x2c: AddressingMode.Absolute,

  0xa9: AddressingMode.Immediate,
  0xa5: AddressingMode.ZeroPage,
  0xb5: AddressingMode.ZeroPage_X,
  0xad: AddressingMode.Absolute,
  0xbd: AddressingMode.Absolute_X,
  0xb9: AddressingMode.Absolute_Y,
  0xa1: AddressingMode.Indirect_X,
  0xb1: AddressingMode.Indirect_Y,

  0xa2: AddressingMode.Immediate,
  0xa6: AddressingMode.ZeroPage,
  0xb6: AddressingMode.ZeroPage_Y,
  0xae: AddressingMode.Absolute,
  0xbe: AddressingMode.Absolute_Y,

  0xa0: AddressingMode.Immediate,
  0xa4: AddressingMode.ZeroPage,
  0xb4: AddressingMode.ZeroPage_X,
  0xac: AddressingMode.Absolute,
  0xbc: AddressingMode.Absolute_X,

  0x85: AddressingMode.ZeroPage,
  0x95: AddressingMode.ZeroPage_X,
  0x8d: AddressingMode.Absolute,
  0x9d: AddressingMode.Absolute_X,
  0x99: AddressingMode.Absolute_Y,
  0x81: AddressingMode.Indirect_X,
  0x91: AddressingMode.Indirect_Y,

  0x86: AddressingMode.ZeroPage,
  0x96: AddressingMode.ZeroPage_Y,
  0x8e: AddressingMode.Absolute,

  0x84: AddressingMode.ZeroPage,
  0x94: AddressingMode.ZeroPage_X,
  0x8c: AddressingMode.Absolute,

  0xd8: AddressingMode.NoneAddressing,
  0x58: AddressingMode.NoneAddressing,
  0xb8: AddressingMode.NoneAddressing,
  0x18: AddressingMode.NoneAddressing,
  0x38: AddressingMode.NoneAddressing,
  0x78: AddressingMode.NoneAddressing,
  0xf8: AddressingMode.NoneAddressing,

  0xaa: AddressingMode.NoneAddressing,
  0xa8: AddressingMode.NoneAddressing,
  0xba: AddressingMode.NoneAddressing,
  0x8a: AddressingMode.NoneAddressing,
  0x9a: AddressingMode.NoneAddressing,
  0x98: AddressingMode.NoneAddressing,

  0x48: AddressingMode.NoneAddressing,
  0x68: AddressingMode.NoneAddressing,
  0x08: AddressingMode.NoneAddressing,
  0x28: AddressingMode.NoneAddressing,

  0xc7: AddressingMode.ZeroPage,
  0xd7: AddressingMode.ZeroPage_X,
  0xcf: AddressingMode.Absolute,
  0xdf: AddressingMode.Absolute_X,
  0xdb: AddressingMode.Absolute_Y,
  0xd3: AddressingMode.Indirect_Y,
  0xc3: AddressingMode.Indirect_X,

  0x27: AddressingMode.ZeroPage,
  0x37: AddressingMode.ZeroPage_X,
  0x2f: AddressingMode.Absolute,
  0x3f: AddressingMode.Absolute_X,
  0x3b: AddressingMode.Absolute_Y,
  0x33: AddressingMode.Indirect_Y,
  0x23: AddressingMode.Indirect_X,

  0x07: AddressingMode.ZeroPage,
  0x17: AddressingMode.ZeroPage_X,
  0x0f: AddressingMode.Absolute,
  0x1f: AddressingMode.Absolute_X,
  0x1b: AddressingMode.Absolute_Y,
  0x03: AddressingMode.Indirect_X,
  0x13: AddressingMode.Indirect_Y,

  0x47: AddressingMode.ZeroPage,
  0x57: AddressingMode.ZeroPage_X,
  0x4f: AddressingMode.Absolute,
  0x5f: AddressingMode.Absolute_X,
  0x5b: AddressingMode.Absolute_Y,
  0x43: AddressingMode.Indirect_X,
  0x53: AddressingMode.Indirect_Y,

  0x80: AddressingMode.Immediate,
  0x82: AddressingMode.Immediate,
  0x89: AddressingMode.Immediate,
  0xc2: AddressingMode.Immediate,
  0xe2: AddressingMode.Immediate,

  0xcb: AddressingMode.Immediate,

  0x6b: AddressingMode.Immediate,

  0xeb: AddressingMode.Immediate,

  0x0b: AddressingMode.Immediate,
  0x2b: AddressingMode.Immediate,

  0x4b: AddressingMode.Immediate,

  0x04: AddressingMode.ZeroPage,
  0x44: AddressingMode.ZeroPage,
  0x64: AddressingMode.ZeroPage,
  0x14: AddressingMode.ZeroPage_X,
  0x34: AddressingMode.ZeroPage_X,
  0x54: AddressingMode.ZeroPage_X,
  0x74: AddressingMode.ZeroPage_X,
  0xd4: AddressingMode.ZeroPage_X,
  0xf4: AddressingMode.ZeroPage_X,
  0x0c: AddressingMode.Absolute,
  0x1c: AddressingMode.Absolute_X,
  0x3c: AddressingMode.Absolute_X,
  0x5c: AddressingMode.Absolute_X,
  0x7c: AddressingMode.Absolute_X,
  0xdc: AddressingMode.Absolute_X,
  0xfc: AddressingMode.Absolute_X,

  0x67: AddressingMode.ZeroPage,
  0x77: AddressingMode.ZeroPage_X,
  0x6f: AddressingMode.Absolute,
  0x7f: AddressingMode.Absolute_X,
  0x7b: AddressingMode.Absolute_Y,
  0x63: AddressingMode.Indirect_X,
  0x73: AddressingMode.Indirect_Y,

  0xe7: AddressingMode.ZeroPage,
  0xf7: AddressingMode.ZeroPage_X,
  0xef: AddressingMode.Absolute,
  0xff: AddressingMode.Absolute_X,
  0xfb: AddressingMode.Absolute_Y,
  0xe3: AddressingMode.Indirect_X,
  0xf3: AddressingMode.Indirect_Y,

  0x02: AddressingMode.NoneAddressing,
  0x12: AddressingMode.NoneAddressing,
  0x22: AddressingMode.NoneAddressing,
  0x32: AddressingMode.NoneAddressing,
  0x42: AddressingMode.NoneAddressing,
  0x52: AddressingMode.NoneAddressing,
  0x62: AddressingMode.NoneAddressing,
  0x72: AddressingMode.NoneAddressing,
  0x92: AddressingMode.NoneAddressing,
  0xb2: AddressingMode.NoneAddressing,
  0xd2: AddressingMode.NoneAddressing,
  0xf2: AddressingMode.NoneAddressing,

  0x1a: AddressingMode.NoneAddressing,
  0x3a: AddressingMode.NoneAddressing,
  0x5a: AddressingMode.NoneAddressing,
  0x7a: AddressingMode.NoneAddressing,
  0xda: AddressingMode.NoneAddressing,

  0xfa: AddressingMode.NoneAddressing,

  0xab: AddressingMode.Immediate,

  0x8b: AddressingMode.Immediate,
  0xbb: AddressingMode.Absolute_Y,
  0x9b: AddressingMode.Absolute_Y,
  0x93: AddressingMode.Indirect_Y,
  0x9f: AddressingMode.Absolute_Y,
  0x9e: AddressingMode.Absolute_Y,
  0x9c: AddressingMode.Absolute_X,

  0xa7: AddressingMode.ZeroPage,
  0xb7: AddressingMode.ZeroPage_Y,
  0xaf: AddressingMode.Absolute,
  0xbf: AddressingMode.Absolute_Y,
  0xa3: AddressingMode.Indirect_X,
  0xb3: AddressingMode.Indirect_Y,

  0x87: AddressingMode.ZeroPage,
  0x97: AddressingMode.ZeroPage_Y,
  0x8f: AddressingMode.Absolute,
  0x83: AddressingMode.Indirect_X,
};
